spring:
  datasource:
    url: jdbc:mysql://thinktripdb.cpqukyis8rth.ap-northeast-2.rds.amazonaws.com:3306/thinktrip
    username: admin
    password: thinktrip123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always


app:
  upload-path: /app/uploads